# author: Fabian Dirscherl
# ... And thanks to jesus riding unicorns puking rainbows and 
# farting glitter - aka @TimeForANinja - it finally works
version: "3.0"
services:
  backend:
    build: ./spring-petclinic-rest/
    ports:
      - "9966:9966"

  frontend:
    build: ./spring-petclinic-angular/
    ports:
      - "8080:8080"
