name: test workflow
on:
  push:
    branches:
      - 'develop'
      - 'main'
  workflow_dispatch:

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: build backend
        run: |
          cd spring-petclinic-rest
          dos2unix mvnw
          ./mvnw spring-boot:run
          echo 'WORKED'