name: Cypress Tests using Cypress Docker Image

on:
  #push:
   # branches:
    #  - 'develop'
     # - 'main'
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: pre-build docker compose images
        run: docker compose -f docker-compose.testing.yml build

      - name: run cypress
        run: docker compose -f docker-compose.testing.yml up --exit-code-from cypress

      - name: upload artifacts
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-cypress
          path: |
            testing/cypress/screenshots
            testing/cypress/videos
